In [2]:
import numpy as np

In [91]:
n = 3 
H = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
w = np.arange(1, n + 1).reshape((n, 1))
v = 0.5*np.arange(1, n + 1).reshape((1, n))
print(H.shape, w.shape, v.shape)

(3, 3) (3, 1) (1, 3)


In [93]:
(v@w@w.T@H).shape

(1, 3)

In [103]:
v@w

array([[7.]])

In [107]:
v.T@w.T@H

array([[15., 18., 21.],
       [30., 36., 42.],
       [45., 54., 63.]])

In [110]:
v@w*H

array([[ 7., 14., 21.],
       [28., 35., 42.],
       [49., 56., 63.]])

# power 1

In [55]:
(H@w).sum()

96

In [56]:
(np.ones((1, 3))@H)@w

array([[96.]])

In [57]:
(np.ones((1, 3))@H).T

array([[12.],
       [15.],
       [18.]])

In [58]:
(H.T@np.ones((1, 3)).T)

array([[12.],
       [15.],
       [18.]])

# power 2

In [190]:
(H@w)**2

array([[ 196],
       [1024],
       [2500]])

In [195]:
U = (H@w)@(w.T@H.T)
e1 = np.array([[1], [0], [0]])
e2 = np.array([[0], [1], [0]])
e3 = np.array([[0], [0], [1]])

U2 = e1.T@U@e1@e1.T + e2.T@U@e2@e2.T + e3.T@U@e3@e3.T
U2

array([[ 196, 1024, 2500]])

In [196]:
result = 0
for i in range(len(w)):
    h = H[i, :].reshape((1, 3))
    H_zeros = np.zeros_like(H)
    H_zeros[i, :] = h
    result += h@w@w.T@H_zeros.T
result

array([[ 196, 1024, 2500]])

In [60]:
np.diag(H@w@w.T@H.T)

array([ 196, 1024, 2500])

In [68]:
U = (H@w)@(w.T@H.T)
e1 = np.array([[1], [0], [0]])
e2 = np.array([[0], [1], [0]])
e3 = np.array([[0], [0], [1]])

U2 = e1.T@U@e1@e1.T + e2.T@U@e2@e2.T + e3.T@U@e3@e3.T
U2

array([[ 196, 1024, 2500]])

In [67]:
U2 = e1.T@(H@w)@(w.T@H.T)@e1@e1.T + e2.T@(H@w)@(w.T@H.T)@e2@e2.T + e3.T@(H@w)@(w.T@H.T)@e3@e3.T
U2
(e1.T@H@w@w.T@H.T@e1)@e1.T

array([[196,   0,   0]])

In [71]:
H

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
(e1.T@H@w@w.T@H.T@e1)@e1.T
e1.T@H

array([[1, 2, 3]])

In [84]:
e1.T@H@w

array([[14]])

In [85]:
e1.T@H@w

array([[14]])

In [86]:
w.T@H.T@e1@e1.T

array([[14,  0,  0]])

In [87]:
e1.T@H@w@w.T@H.T@e1@e1.T

array([[196,   0,   0]])

In [79]:
H.T@e3@e3.T

array([[0, 0, 7],
       [0, 0, 8],
       [0, 0, 9]])

In [245]:
2*H.T@H@w

array([[168],
       [168],
       [168]])

In [83]:
w.shape

(3, 1)

In [80]:
w@w.T

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

# power of 3

In [212]:
(h.T@h).T

array([[49, 56, 63],
       [56, 64, 72],
       [63, 72, 81]])

In [207]:
(H + H_zeros).T
(H.T + H_zeros.T)

array([[ 1,  4, 14],
       [ 2,  5, 16],
       [ 3,  6, 18]])

In [204]:
(h.T@w.T@H.T).T

array([[ 98, 112, 126],
       [224, 256, 288],
       [350, 400, 450]])

In [205]:
(H@w@h)

array([[ 98, 112, 126],
       [224, 256, 288],
       [350, 400, 450]])

In [197]:
(H@w)**3

array([[  2744],
       [ 32768],
       [125000]], dtype=int32)

In [199]:
result = 0
for i in range(len(w)):
    h = H[i, :].reshape((1, 3))
    H_tilte = h.T@h
    H_zeros = np.zeros_like(H_tilte)
    H_zeros[i, :] = h
    result += w.T@H_tilte@w@w.T@H_zeros.T
result

array([[  2744,  32768, 125000]])

In [169]:
h = H[1, :].reshape((1, 3))
h

array([[4, 5, 6]])

In [173]:
w.shape

(3, 1)

In [175]:
h.T@h

array([[16, 20, 24],
       [20, 25, 30],
       [24, 30, 36]])

In [172]:
w.T@h.T@h@w

array([[1024]])

In [161]:
h = H[1, :].reshape((1, 3))
(h@w@w.T@h.T)
(w.T@h.T@h@w)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [146]:
e2.T@(H@w)**2

array([[1024]])

In [142]:
e1 = np.array([[1], [0], [0]])
e2 = np.array([[0], [1], [0]])
e3 = np.array([[0], [0], [1]])
np.diag((H@w)@(w.T@H.T))@(H@w).T

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [143]:
np.diag((H@w)@(w.T@H.T)).reshape((3, 1))@(H@w).T
np.diag((H@w)@(w.T@H.T)).reshape((3, 1))@w.T@H.T

array([[  2744,   6272,   9800],
       [ 14336,  32768,  51200],
       [ 35000,  80000, 125000]])

In [233]:
w@w.T

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [231]:
(w.T@H.T@(H@w).T@H.T@w)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)